function thinningVideoFrame(I, dName, vID, minlength)
%-----Thin it by bwmorph and discompose it--------------------------------
% https://www.peterkovesi.com/matlabfns/LineSegments/example/index.html

A   = I;
B   = ~I(:, :,1);

% Discard contours less than 10 pixels long.
[edgelist, ~] = edgelink(B, 10);

% Clean up a set of edge lists generated by edgelink or lineseg so that
% isolated edges and spurs that are shorter than a minimum length are removed.
nedgelist = cleanedgelist(edgelist, minlength);

% Save the images
color               = hsv(size(nedgelist,2));
color               = color(randperm(size(nedgelist,2)), :);
segimg              = zeros(size(A,1),size(A,2),3);
segimg2             = zeros(size(A,1),size(A,2),3);
segimg(:, :, :)     = 1;
segimg2(:, :, :)    = 1;

for k=1:size(nedgelist,2)
    for m=1:size(nedgelist{1,k})
        segimg(nedgelist{1,k}(m,1), nedgelist{1,k}(m,2), :)         = color(k, :);
        segimg(nedgelist{1,k}(m,1)-1, nedgelist{1,k}(m,2)-1, :)     = color(k, :);
        segimg(nedgelist{1,k}(m,1)-1, nedgelist{1,k}(m,2), :)       = color(k, :);
        segimg(nedgelist{1,k}(m,1), nedgelist{1,k}(m,2)-1, :)       = color(k, :);
        segimg(nedgelist{1,k}(m,1)+1, nedgelist{1,k}(m,2), :)       = color(k, :);
        segimg(nedgelist{1,k}(m,1), nedgelist{1,k}(m,2)+1, :)       = color(k, :);
        segimg(nedgelist{1,k}(m,1)+1, nedgelist{1,k}(m,2)+1, :)     = color(k, :);
        segimg(nedgelist{1,k}(m,1)+1, nedgelist{1,k}(m,2)-1, :)     = color(k, :);
        segimg(nedgelist{1,k}(m,1)-1, nedgelist{1,k}(m,2)+1, :)     = color(k, :);
        
        segimg2(nedgelist{1,k}(m,1), nedgelist{1,k}(m,2), :)        = 0;
        segimg2(nedgelist{1,k}(m,1)-1, nedgelist{1,k}(m,2)-1, :)    = 0;
        segimg2(nedgelist{1,k}(m,1)-1, nedgelist{1,k}(m,2), :)      = 0;
        segimg2(nedgelist{1,k}(m,1), nedgelist{1,k}(m,2)-1, :)      = 0;
        segimg2(nedgelist{1,k}(m,1)+1, nedgelist{1,k}(m,2), :)      = 0;
        segimg2(nedgelist{1,k}(m,1), nedgelist{1,k}(m,2)+1, :)      = 0;
        segimg2(nedgelist{1,k}(m,1)+1, nedgelist{1,k}(m,2)+1, :)    = 0;
        segimg2(nedgelist{1,k}(m,1)+1, nedgelist{1,k}(m,2)-1, :)    = 0;
        segimg2(nedgelist{1,k}(m,1)-1, nedgelist{1,k}(m,2)+1, :)    = 0;
        
    end
end
imwrite(I, fullfile(dName, strcat( 'view', num2str(vID), '_bd0.png')));       % original image
imwrite(segimg2, fullfile(dName, strcat('view', num2str(vID), '_bd1.png')));  % black-white image
imwrite(segimg, fullfile(dName, strcat('view', num2str(vID), '_bd2.png')));   % colorful image

% Save the curve points
fileID = fopen(fullfile(dName, strcat('curvepoints', num2str(vID), '.txt')), 'w');
fprintf(fileID, '%d\n', size(nedgelist, 2)); 

for k = 1:size(nedgelist, 2)
    for m = 1:size(nedgelist{1,k},1)
        fprintf(fileID, '%d\t%d\t%d\n', k, nedgelist{1,k}(m,1), nedgelist{1,k}(m,2));% 第几段|点坐标x|点坐标y
    end
end
fclose(fileID);